[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[deploy.env]
NODE_ENV = "production"

[deploy.lifecycle]
predeploy = "npm run build"

[build.env]
NODE_ENV = "production"

[install]
cmd = "npm install" 