services:
  - type: web
    name: nutriverse-ai
    env: node
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true

  - type: web
    name: nutriverse-ai-frontend
    env: static
    buildCommand: npm install && npx vite build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://nutriverse-ai.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeploy: true 